#!/usr/bin/env python

import sys
import os
from ribonorma import ribonorma

arguments = sys.argv + [""]
classed_arguments = {}

try:
    for i in range(len(arguments)):

        argument = arguments[i]

        if argument.startswith("-"):

            classed_arguments[argument[1:]] = arguments[i + 1]

    if "h" in classed_arguments.keys():
        help_output = open("help_pages/ribonorma-stats.txt", "r").read()
        print(help_output)
        os._exit(1)
